- name: Install brew packages for php web development
  homebrew: name={{ item }} state=present
  with_items:
  - node
  - homebrew/php/php71
- name: Clone Coolblue repositories from your own github
  git: repo="git@github.com:{{ github_login }}/{{ item }}.git" dest="/Users/{{ mac_login }}/Projects/{{ item }}" update=no
  with_items: "{{ forked_php_web_repositories }}"
- name: Add Coolblue upstream to repositories
  command: "git remote add upstream git@github.com:coolblue-development/{{ item }}.git"
  args:
    chdir: "/Users/{{ mac_login }}/Projects/{{ item }}"
  with_items: "{{ forked_php_web_repositories }}"
  ignore_errors: true
