- name: Install kdiff3 and git
  homebrew: name={{ item }} state=present
  with_items:
  - git
  - kdiff3
- name: Set kdiff3 as git mergetool
  command: "git config --global merge.tool kdiff3"
- name: Add a .netrc file to the home directory
  template: src=netrc dest=/Users/{{ mac_login }}/.netrc
- name: Set git aliases
  command: 'git config --global alias.{{ item.alias }} "{{ item. command }}"'
  with_items: git_aliases
